"""
build_derived.py -- builds the derived/ layer from the authoritative/ layer.

For each authoritative version it writes derived/<id>/<ver>/:
  * structure.json        -- deterministic parse into units + detected citations
  * concepts.json         -- neutral concept tags (curated from concepts.TAGS if present,
                             else a keyword fallback from concepts.KW)
  * derived-metadata.yaml -- one provenance record per derived artifact
  * (translations/*.md, if present, are registered as unofficial translation artifacts)

Plus corpus-level products: derived/concept-index.json + .md, docs/concept-vocabulary.md.

ALL output is DERIVED and UNOFFICIAL, traceable to each authoritative text hash.
Everything domain-specific comes from concepts.py -- this file is pure mechanism.
"""
import json, os, re, sys, datetime
import yaml
sys.path.insert(0, os.path.dirname(__file__))
from hashing import sha256_bytes, normalize_text_bytes  # noqa
import concepts

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUTH = os.path.join(REPO, "authoritative")
DER = os.path.join(REPO, "derived")
DOCS = os.path.join(REPO, "docs")
TODAY = datetime.date.today().isoformat()
DISCLAIMER = ("Derived, unofficial content generated by the corpus toolkit. NOT the authoritative "
              "source text. See the linked authoritative source and its authentic-language text for "
              "anything legally operative.")
GENERATOR = getattr(concepts, "GENERATOR", "corpus-toolkit build_derived")
VOCAB = concepts.VOCAB
MODEL_TAGS = getattr(concepts, "TAGS", {})
KW = getattr(concepts, "KW", {})
HEADERS = getattr(concepts, "UNIT_HEADERS", ["Article", "Section", "Rule", "Clause"])
CITE_PATS = getattr(concepts, "CITATION_PATTERNS", [])

hdr_re = re.compile(r"^(" + "|".join(map(re.escape, HEADERS)) + r")\s+([IVXLCDM]+|[A-Z]\.\d+|\d+[A-Za-z\-]*)\b")
num_re = re.compile(r"^(\d+)\.\s")
_EXTRA = getattr(concepts, "HEADER_PATTERNS_EXTRA", [])
hdr_extra = re.compile("^(?:" + "|".join(_EXTRA) + ")") if _EXTRA else None

def _hdr_match(p):
    """Match a top-level provision start: Latin 'Article N' OR a non-Latin (RU/ZH) header."""
    m = hdr_re.match(p)
    if m: return m, m.group(1), m.group(m.lastindex)
    if hdr_extra:
        m2 = hdr_extra.match(p)
        if m2: return m2, None, None
    return None, None, None

def split_units(body):
    paras = [p.strip() for p in body.split("\n\n") if p.strip()]
    n_hdr = sum(1 for p in paras if _hdr_match(p)[0]); n_num = sum(1 for p in paras if num_re.match(p))
    if n_hdr >= 2: mode = "header"
    elif n_num >= 2: mode = "numbered"
    else: return "document", [{"number": None, "label": "(whole text)", "text": "\n\n".join(paras)}]
    units, cur, pre, first_kw = [], None, [], None
    for p in paras:
        if mode == "header":
            m, kw, num = _hdr_match(p)
        else:
            m = num_re.match(p); kw = None; num = m.group(1) if m else None
        if m:
            if cur: units.append(cur)
            if mode == "header" and first_kw is None and kw: first_kw = kw
            label = p.split("\n")[0].strip() if mode == "header" else "Paragraph " + num
            cur = {"number": num, "label": label, "text": p}
        elif cur: cur["text"] += "\n\n" + p
        else: pre.append(p)
    if cur: units.append(cur)
    if pre: units.insert(0, {"number": None, "label": "preamble/chapeau", "text": "\n\n".join(pre)})
    utype = (first_kw.lower() if mode == "header" and first_kw else ("paragraph" if mode == "numbered" else "unit"))
    return utype, units

def detect_citations(body):
    return sorted({m if isinstance(m, str) else m[0] for pat in CITE_PATS for m in re.findall(pat, body)})

def keyword_tags(units):
    tags, doc = [], set()
    for u in units:
        low = u["text"].lower(); hits = [c for c, kws in KW.items() if any(k in low for k in kws)]
        if hits: tags.append({"unit": u["label"], "concepts": hits}); doc.update(hits)
    return tags, sorted(doc)

index = {c: [] for c in VOCAB}
records = []
for root, _, files in os.walk(AUTH):
    if "metadata.yaml" not in files: continue
    meta = yaml.safe_load(open(os.path.join(root, "metadata.yaml"), encoding="utf-8"))
    tpath = os.path.join(root, "text.txt")
    if not os.path.exists(tpath): continue
    full = open(tpath, encoding="utf-8").read()
    body = full.split("\n\n", 1)[1] if "\n\n" in full else full
    cid, ver, sh = meta["corpus_id"], str(meta["version_id"]), meta.get("short_title", meta["corpus_id"])
    src_hash = meta["text_sha256"]
    utype, units = split_units(body)

    if cid in MODEL_TAGS:
        tags = [{"unit": u, "concepts": cs} for u, cs in MODEL_TAGS[cid]]
        doc_concepts = sorted({c for _, cs in MODEL_TAGS[cid] for c in cs})
        method, gen, cnote = "curated", GENERATOR, "Curated tagging at provision granularity; not legally reviewed."
    else:
        tags, doc_concepts = keyword_tags(units)
        method, gen, cnote = "rule_based", "build_derived.py (keyword fallback)", "Keyword fallback; expect false pos/neg."

    for t in tags:
        for c in t["concepts"]:
            index.setdefault(c, []).append({"corpus_id": cid, "short_title": sh, "version_id": ver, "unit": t["unit"]})

    outdir = os.path.join(DER, cid, ver); os.makedirs(outdir, exist_ok=True)
    json.dump({"_derived": True, "_disclaimer": DISCLAIMER, "corpus_id": cid, "version_id": ver,
               "title": meta["title"], "document_type": meta.get("document_type"), "adoption_date": meta.get("adoption_date"),
               "unit_type": utype, "unit_count": len(units), "units": units, "citations_detected": detect_citations(body)},
              open(os.path.join(outdir, "structure.json"), "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    json.dump({"_derived": True, "_disclaimer": DISCLAIMER, "corpus_id": cid, "version_id": ver,
               "concept_vocabulary": list(VOCAB), "tagging_method": method,
               "document_concepts": doc_concepts, "tags": tags},
              open(os.path.join(outdir, "concepts.json"), "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    dmeta = [
      {"derived_id": f"{cid}/{ver}/structure", "derived_type": "structure_extraction", "artifact_file": "structure.json",
       "source_corpus_id": cid, "source_version_id": ver, "source_text_sha256": src_hash,
       "generation_method": "rule_based", "generator": "build_derived.py (structure)", "generation_date": TODAY,
       "review_status": "unreviewed", "reviewed_by": None, "license": "CC-BY-4.0",
       "confidence_note": f"Deterministic parse into {len(units)} {utype} unit(s).", "disclaimer": DISCLAIMER},
      {"derived_id": f"{cid}/{ver}/concepts", "derived_type": "concept_tags", "artifact_file": "concepts.json",
       "source_corpus_id": cid, "source_version_id": ver, "source_text_sha256": src_hash,
       "generation_method": method, "generator": gen, "generation_date": TODAY,
       "review_status": "unreviewed", "reviewed_by": None, "license": "CC-BY-4.0",
       "confidence_note": cnote, "disclaimer": DISCLAIMER},
    ]
    tdir = os.path.join(outdir, "translations")
    if os.path.isdir(tdir):
        for tf in sorted(os.listdir(tdir)):
            if tf.endswith(".md"):
                lang = tf[:-3]
                dmeta.append({"derived_id": f"{cid}/{ver}/translation-{lang}", "derived_type": "translation",
                    "artifact_file": f"translations/{tf}", "source_corpus_id": cid, "source_version_id": ver,
                    "source_text_sha256": src_hash, "generation_method": "model", "generator": GENERATOR,
                    "generation_date": TODAY, "review_status": "unreviewed", "reviewed_by": None,
                    "license": "CC-BY-4.0",
                    "confidence_note": f"Unofficial machine-draft {lang} translation; not legally operative.",
                    "disclaimer": DISCLAIMER})
    yaml.safe_dump(dmeta, open(os.path.join(outdir, "derived-metadata.yaml"), "w", encoding="utf-8"),
                   sort_keys=False, allow_unicode=True)
    records.append((cid, ver, utype, len(units), len(doc_concepts)))

os.makedirs(DER, exist_ok=True)
json.dump({"_derived": True, "_disclaimer": DISCLAIMER, "vocabulary": VOCAB, "index": index},
          open(os.path.join(DER, "concept-index.json"), "w", encoding="utf-8"), indent=2, ensure_ascii=False)
md = ["# Concept Index (derived, unofficial)", "", f"_{DISCLAIMER}_", "",
      "For each neutral concept, the provisions across the corpus that address it. Concepts describe what a "
      "provision is *about*; they take no position on any doctrine.", ""]
for c in VOCAB:
    entries = index.get(c, [])
    md.append(f"## {c}"); md.append(f"*{VOCAB[c]}*"); md.append("")
    if not entries: md.append("_(no provisions tagged)_\n"); continue
    by_inst = {}
    for e in entries: by_inst.setdefault((e["short_title"], e["corpus_id"]), []).append(e["unit"])
    for (sh, cid), us in by_inst.items(): md.append(f"- **{sh}** (`{cid}`): " + "; ".join(us))
    md.append("")
open(os.path.join(DER, "concept-index.md"), "w", encoding="utf-8").write("\n".join(md) + "\n")

os.makedirs(DOCS, exist_ok=True)
vmd = ["# Concept Vocabulary", "",
       "The neutral concepts used to tag provisions in the derived layer. Each describes what a provision "
       "is *about*; the vocabulary is doctrine-agnostic. Tagging is derived, unofficial, and traceable to "
       "each authoritative text.", ""]
for c, d in VOCAB.items(): vmd.append(f"- **`{c}`** — {d}")
open(os.path.join(DOCS, "concept-vocabulary.md"), "w", encoding="utf-8").write("\n".join(vmd) + "\n")

print(f"Rebuilt derived for {len(records)} instrument(s).")
for c in VOCAB: print(f"  {c:42s} {len(index.get(c, [])):2d}")
